spring:
  security:
    oauth2:
      client:
        registration:
         google:
          clientId: <clientID>
          clientSecret: <client secret>
          scope:
           - email
           - profile
server:
   port: 2233
